return {
	{
		"L3MON4D3/LuaSnip",
		-- follow latest release.
		version = "v2.*", -- Replace <CurrentMajor> by the latest released major (first number of latest release)
		-- install jsregexp (optional!).
		build = "make install_jsregexp",

		dependencies = { "rafamadriz/friendly-snippets" },

		config = function()
			local ls = require("luasnip")

			--[[
			LuaSnip components explained:
			
			s = snippet - Creates a new snippet
			t = text_node - Static text that gets inserted
			i = insert_node - Places where you can type (like placeholders)
			f = function_node - Dynamic content generated by a function
			c = choice_node - Multiple options you can cycle through
			rep = repeat - Repeats the content of another node
			fmt = format - Easier way to write snippets with {} placeholders
			
			Basic usage:
			1. Type the trigger word (e.g., "hello")
			2. Press <C-s>e to expand the snippet
			3. Use <C-s>; to jump forward through placeholders
			4. Use <C-s>, to jump backward through placeholders
			]]

			-- Import the snippet components we'll use
			local s = ls.snippet
			local t = ls.text_node
			local i = ls.insert_node
			local c = ls.choice_node
			local extras = require("luasnip.extras")
			local rep = extras.rep
			local fmt = require("luasnip.extras.fmt").fmt
			local f = ls.function_node

			-- Load friendly-snippets (a collection of snippets for many languages)
			require("luasnip.loaders.from_vscode").lazy_load()

			ls.filetype_extend("javascript", { "jsdoc" })
			ls.filetype_extend("python", { "python" })

			-- Markdown snippets
			ls.add_snippets("markdown", {
				-- Checkbox snippet: type "jcb" and expand to get "- [ ]()"
				-- Now with two jump points
				s(
					"nj",
					fmt("- [{}]({})", {
						i(1, " "), -- First placeholder between the brackets
						i(2), -- Second placeholder between the parentheses
					})
				),
				-- Heading with choice: type "hd" and use <C-E> to cycle through levels
				s(
					"hd",
					fmt("{} {}", {
						c(1, {
							t("#"),
							t("##"),
							t("###"),
							t("####"),
							t("#####"),
						}),
						i(2, "Heading"),
					})
				),
			})

			-- Example Lua snippets
			ls.add_snippets("lua", {
				s("hello", t("Hello, World!")),
				s(
					"fn",
					fmt("function {}({})\n\t{}\nend", {
						i(1, "name"),
						i(2, "args"),
						i(3, "-- body"),
					})
				),
			})

			-- All filetypes
			ls.add_snippets("all", {
				s(
					"date",
					f(function()
						return os.date("%Y-%m-%d")
					end)
				),
			})

			vim.keymap.set({ "i" }, "<C-k>", function()
				ls.expand()
			end, { silent = true })
			vim.keymap.set({ "i", "s" }, "<C-l>", function()
				ls.jump(1)
			end, { silent = true })
			vim.keymap.set({ "i", "s" }, "<C-j>", function()
				ls.jump(-1)
			end, { silent = true })

			vim.keymap.set({ "i", "s" }, "<C-e>", function()
				if ls.choice_active() then
					ls.change_choice(1)
				end
			end, { silent = true })
		end,
	},
}
